openclaw cron add \
  --name "Data Guardian PII Scanner" \
  --agent safeclaw \
  --every 15m \
  --wake now \
  --session isolated \
  --model "vllm/Qwen/Qwen3-32B" \
  --deliver \
  --channel slack \
  --to "[SLACK-CHANNEL-ID]" \
  --message "Complete the task in \`pii-scanner/TASK.md\`. After completing the task, your task output Slack message must start with ':stainedglass: This content is protected by Protopia Stained Glass :stainedglass: \n\n'."